# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import test_pb2 as test__pb2


class HelloStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HelloLys = channel.unary_unary(
                '/test.Hello/HelloLys',
                request_serializer=test__pb2.HelloReq.SerializeToString,
                response_deserializer=test__pb2.HelloRes.FromString,
                )


class HelloServicer(object):
    """Missing associated documentation comment in .proto file"""

    def HelloLys(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HelloLys': grpc.unary_unary_rpc_method_handler(
                    servicer.HelloLys,
                    request_deserializer=test__pb2.HelloReq.FromString,
                    response_serializer=test__pb2.HelloRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.Hello', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Hello(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def HelloLys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.Hello/HelloLys',
            test__pb2.HelloReq.SerializeToString,
            test__pb2.HelloRes.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
